/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.63 from the
 * contents of Info.xs. Do not edit this file, edit Info.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Info.xs"
#ifndef _GNU_SOURCE
#define _GNU_SOURCE /* glibc / Linux */
#endif
#ifndef __EXTENSIONS__
#define __EXTENSIONS__ 1 /* Solaris/illumos */
#endif
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"
#include <string.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

/* ===========================================================================
 * Structure::Info -- the parts of reading a PDB file that are worth doing in C.
 *
 * A PDB file is one record per line, and every field sits at a fixed column
 * range (the format is punched-card old).  Two things about that make XS pay
 * for itself here, and only two:
 *
 *   1. the coordinate section is enormous -- the largest file in PDBbind
 *      v2020 is 33 MB, ~400,000 ATOM/HETATM lines -- and every one of those
 *      lines wants a dozen substr()s and three numeric conversions.  Done in
 *      Perl that is a dozen SVs per line born and buried;
 *   2. residue names are looked up constantly (three letters -> one letter,
 *      and "is this an amino acid, a nucleotide or water?"), which is a
 *      switch on three bytes in C and a hash lookup plus a sub call in Perl.
 *
 * So C does exactly that: one pass over the bytes, ATOM/HETATM split into
 * parallel column arrays (a "columnar" result -- one array per field, not one
 * hash per atom, which keeps peak memory down by roughly an order of
 * magnitude), residue boundaries marked as it goes, and every other record
 * handed back as raw lines grouped by record name.
 *
 * The header records (HEADER, COMPND, REMARK, SEQRES, ...) are parsed in
 * Perl.  There are a few dozen of them, they are irregular, and they are the
 * part most likely to need fixing later; none of that belongs in C.
 * ======================================================================== */

/* --- residue table -------------------------------------------------------
 * One table serves aa3to1(), res1() and res_type(), so the three can never
 * disagree about what a residue is.  Keyed on the three-byte name packed into
 * an int, left-padded with blanks, so that "ALA", " DA" and "  A" are all one
 * switch on an integer. */
#define RT_OTHER 0
#define RT_AA    1
#define RT_NUC   2
#define RT_WATER 3

#define K3(a, b, c) (((unsigned)(a) << 16) | ((unsigned)(b) << 8) | (unsigned)(c))

typedef struct {
	char one;           /* single-letter code; '\0' when there isn't one */
	unsigned char type; /* RT_* */
} res_info;

/* pack a (possibly blank-padded, possibly short) residue name into a key */
static unsigned res_key(const char *s, STRLEN len)
{
	char b[3];
	STRLEN i;
	while (len && (*s == ' ' || *s == '\t')) { s++; len--; }
	while (len && (s[len - 1] == ' ' || s[len - 1] == '\t')) len--;
	if (len == 0 || len > 3) return 0;
	b[0] = b[1] = b[2] = ' ';
	for (i = 0; i < len; i++) b[3 - len + i] = (char)toupper((unsigned char)s[i]);
	return K3((unsigned char)b[0], (unsigned char)b[1], (unsigned char)b[2]);
}

/* res_lookup() -- classify a residue name.  Returns 1 when the name is known,
 * 0 when it is not (a ligand, an ion, a sugar: anything the caller has to
 * work out for itself from the atoms). */
static int res_lookup(const char *s, STRLEN len, res_info *out)
{
	char one;
	unsigned char type = RT_AA;
	switch (res_key(s, len)) {
		/* the twenty, plus the ambiguity codes the format allows */
		case K3('A','L','A'): one = 'A'; break;
		case K3('A','R','G'): one = 'R'; break;
		case K3('A','S','N'): one = 'N'; break;
		case K3('A','S','P'): one = 'D'; break;
		case K3('C','Y','S'): one = 'C'; break;
		case K3('G','L','N'): one = 'Q'; break;
		case K3('G','L','U'): one = 'E'; break;
		case K3('G','L','Y'): one = 'G'; break;
		case K3('H','I','S'): one = 'H'; break;
		case K3('I','L','E'): one = 'I'; break;
		case K3('L','E','U'): one = 'L'; break;
		case K3('L','Y','S'): one = 'K'; break;
		case K3('M','E','T'): one = 'M'; break;
		case K3('P','H','E'): one = 'F'; break;
		case K3('P','R','O'): one = 'P'; break;
		case K3('S','E','R'): one = 'S'; break;
		case K3('T','H','R'): one = 'T'; break;
		case K3('T','R','P'): one = 'W'; break;
		case K3('T','Y','R'): one = 'Y'; break;
		case K3('V','A','L'): one = 'V'; break;
		case K3('A','S','X'): one = 'B'; break; /* ASP or ASN     */
		case K3('G','L','X'): one = 'Z'; break; /* GLU or GLN     */
		case K3('X','L','E'): one = 'J'; break; /* LEU or ILE     */
		case K3('S','E','C'): one = 'U'; break; /* selenocysteine */
		case K3('P','Y','L'): one = 'O'; break; /* pyrrolysine    */
		case K3('U','N','K'): one = 'X'; break;
		case K3('X','A','A'): one = 'X'; break;

		/* modified residues, mapped to the parent they were made from.  A
		 * structure that soaked in selenomethionine is still the same
		 * sequence, and a sequence with an 'X' every seventh position is
		 * no use to anyone. */
		case K3('M','S','E'): one = 'M'; break; /* selenomethionine */
		case K3('M','H','O'): one = 'M'; break;
		case K3('F','M','E'): one = 'M'; break;
		case K3('C','X','M'): one = 'M'; break;
		case K3('S','M','E'): one = 'M'; break;
		case K3('M','E','D'): one = 'M'; break;
		case K3('C','S','O'): one = 'C'; break;
		case K3('C','S','D'): one = 'C'; break;
		case K3('C','S','S'): one = 'C'; break;
		case K3('C','S','X'): one = 'C'; break;
		case K3('C','S','W'): one = 'C'; break;
		case K3('C','M','E'): one = 'C'; break;
		case K3('C','M','T'): one = 'C'; break;
		case K3('C','Y','X'): one = 'C'; break;
		case K3('C','A','S'): one = 'C'; break;
		case K3('C','A','F'): one = 'C'; break;
		case K3('O','C','S'): one = 'C'; break;
		case K3('S','M','C'): one = 'C'; break;
		case K3('S','N','C'): one = 'C'; break;
		case K3('Y','C','M'): one = 'C'; break;
		case K3('S','E','P'): one = 'S'; break; /* phosphoserine    */
		case K3('S','A','C'): one = 'S'; break;
		case K3('T','P','O'): one = 'T'; break; /* phosphothreonine */
		case K3('P','T','R'): one = 'Y'; break; /* phosphotyrosine  */
		case K3('T','Y','S'): one = 'Y'; break;
		case K3('T','Y','I'): one = 'Y'; break;
		case K3('T','Y','Q'): one = 'Y'; break;
		case K3('T','P','Q'): one = 'Y'; break;
		case K3('P','A','Q'): one = 'Y'; break;
		case K3('S','T','Y'): one = 'Y'; break;
		case K3('I','Y','R'): one = 'Y'; break;
		case K3('K','C','X'): one = 'K'; break;
		case K3('L','L','P'): one = 'K'; break;
		case K3('M','L','Y'): one = 'K'; break;
		case K3('M','L','Z'): one = 'K'; break;
		case K3('M','3','L'): one = 'K'; break;
		case K3('A','L','Y'): one = 'K'; break;
		case K3('L','Y','Z'): one = 'K'; break;
		case K3('H','Y','P'): one = 'P'; break; /* hydroxyproline */
		case K3('H','Y','3'): one = 'P'; break;
		case K3('P','C','A'): one = 'E'; break; /* pyroglutamate  */
		case K3('C','G','U'): one = 'E'; break;
		case K3('G','M','A'): one = 'E'; break;
		case K3('H','I','C'): one = 'H'; break;
		case K3('H','I','D'): one = 'H'; break;
		case K3('H','I','E'): one = 'H'; break;
		case K3('H','I','P'): one = 'H'; break;
		case K3('H','S','D'): one = 'H'; break;
		case K3('H','S','E'): one = 'H'; break;
		case K3('H','S','P'): one = 'H'; break;
		case K3('M','H','S'): one = 'H'; break;
		case K3('N','E','P'): one = 'H'; break;
		case K3('A','I','B'): one = 'A'; break;
		case K3('A','B','A'): one = 'A'; break;
		case K3('A','L','M'): one = 'A'; break;
		case K3('A','Y','A'): one = 'A'; break;
		case K3('B','A','L'): one = 'A'; break;
		case K3('S','A','R'): one = 'G'; break; /* sarcosine */
		case K3('M','L','E'): one = 'L'; break;
		case K3('N','L','E'): one = 'L'; break;
		case K3('M','V','A'): one = 'V'; break;
		case K3('C','I','R'): one = 'R'; break; /* citrulline */
		case K3('O','R','N'): one = 'X'; break; /* ornithine  */
		case K3('D','A','B'): one = 'X'; break;
		case K3('T','R','O'): one = 'W'; break;
		case K3('P','H','I'): one = 'F'; break;
		case K3('P','H','L'): one = 'F'; break;
		case K3('M','E','A'): one = 'F'; break;

		/* D-amino acids -- common in the peptide ligands this was written
		 * for, and they are the same letter as their L partner */
		case K3('D','A','L'): one = 'A'; break;
		case K3('D','A','R'): one = 'R'; break;
		case K3('D','S','G'): one = 'N'; break;
		case K3('D','A','S'): one = 'D'; break;
		case K3('D','C','Y'): one = 'C'; break;
		case K3('D','G','N'): one = 'Q'; break;
		case K3('D','G','L'): one = 'E'; break;
		case K3('D','H','I'): one = 'H'; break;
		case K3('D','I','L'): one = 'I'; break;
		case K3('D','L','E'): one = 'L'; break;
		case K3('D','L','Y'): one = 'K'; break;
		case K3('D','P','N'): one = 'F'; break;
		case K3('D','P','R'): one = 'P'; break;
		case K3('D','S','N'): one = 'S'; break;
		case K3('D','T','H'): one = 'T'; break;
		case K3('D','T','R'): one = 'W'; break;
		case K3('D','T','Y'): one = 'Y'; break;
		case K3('D','V','A'): one = 'V'; break;
		case K3('D','I','V'): one = 'V'; break;

		/* nucleotides: DNA (" DA"), RNA ("  A"), and the pre-v3 spellings */
		case K3(' ','D','A'): one = 'A'; type = RT_NUC; break;
		case K3(' ','D','C'): one = 'C'; type = RT_NUC; break;
		case K3(' ','D','G'): one = 'G'; type = RT_NUC; break;
		case K3(' ','D','T'): one = 'T'; type = RT_NUC; break;
		case K3(' ','D','U'): one = 'U'; type = RT_NUC; break;
		case K3(' ','D','I'): one = 'I'; type = RT_NUC; break;
		case K3(' ',' ','A'): one = 'A'; type = RT_NUC; break;
		case K3(' ',' ','C'): one = 'C'; type = RT_NUC; break;
		case K3(' ',' ','G'): one = 'G'; type = RT_NUC; break;
		case K3(' ',' ','T'): one = 'T'; type = RT_NUC; break;
		case K3(' ',' ','U'): one = 'U'; type = RT_NUC; break;
		case K3(' ',' ','I'): one = 'I'; type = RT_NUC; break;
		case K3(' ',' ','N'): one = 'N'; type = RT_NUC; break;
		case K3('A','D','E'): one = 'A'; type = RT_NUC; break;
		case K3('C','Y','T'): one = 'C'; type = RT_NUC; break;
		case K3('G','U','A'): one = 'G'; type = RT_NUC; break;
		case K3('T','H','Y'): one = 'T'; type = RT_NUC; break;
		case K3('U','R','I'): one = 'U'; type = RT_NUC; break;
		case K3('P','S','U'): one = 'U'; type = RT_NUC; break; /* pseudouridine */
		case K3('H','2','U'): one = 'U'; type = RT_NUC; break;
		case K3('4','S','U'): one = 'U'; type = RT_NUC; break;
		case K3('5','M','U'): one = 'T'; type = RT_NUC; break;
		case K3('5','M','C'): one = 'C'; type = RT_NUC; break;
		case K3('O','M','C'): one = 'C'; type = RT_NUC; break;
		case K3('1','M','A'): one = 'A'; type = RT_NUC; break;
		case K3('2','M','G'): one = 'G'; type = RT_NUC; break;
		case K3('7','M','G'): one = 'G'; type = RT_NUC; break;
		case K3('1','M','G'): one = 'G'; type = RT_NUC; break;
		case K3('M','2','G'): one = 'G'; type = RT_NUC; break;
		case K3('O','M','G'): one = 'G'; type = RT_NUC; break;

		/* water, under every name it gets written with */
		case K3('H','O','H'): one = '\0'; type = RT_WATER; break;
		case K3('W','A','T'): one = '\0'; type = RT_WATER; break;
		case K3('D','O','D'): one = '\0'; type = RT_WATER; break;
		case K3('H','2','O'): one = '\0'; type = RT_WATER; break;
		case K3('S','O','L'): one = '\0'; type = RT_WATER; break;
		case K3('T','I','P'): one = '\0'; type = RT_WATER; break;

		default: return 0;
	}
	out->one  = one;
	out->type = type;
	return 1;
}

/* --- column fields -------------------------------------------------------
 * Every accessor below clips to the line's real length first: PDB files in
 * the wild are right-trimmed, so a line can stop before the element column
 * (or before the B-factor) and that is not an error. */

static STRLEN trim_ptr(const char **sp, STRLEN len)
{
	const char *s = *sp;
	while (len && (*s == ' ' || *s == '\t')) { s++; len--; }
	while (len && (s[len - 1] == ' ' || s[len - 1] == '\t')) len--;
	*sp = s;
	return len;
}

/* fld() -- the trimmed contents of columns [from, to], zero-based inclusive */
static STRLEN fld(const char *line, STRLEN llen, STRLEN from, STRLEN to, const char **out)
{
	const char *s;
	STRLEN n;
	*out = line;
	if (from >= llen) return 0;
	if (to >= llen) to = llen - 1;
	s = line + from;
	n = to - from + 1;
	n = trim_ptr(&s, n);
	*out = s;
	return n;
}

/* str2iv() -- integers, exactly, without going through a double.  '*****'
 * (what a serial number becomes once it overflows five columns) and anything
 * else non-numeric report failure rather than a wrong number. */
static int str2iv(const char *s, STRLEN n, IV *out)
{
	int neg = 0, seen = 0;
	IV v = 0;
	STRLEN i = 0;
	if (i < n && (s[i] == '+' || s[i] == '-')) { neg = (s[i] == '-'); i++; }
	for (; i < n; i++) {
		if (!isdigit((unsigned char)s[i])) return 0;
		v = v * 10 + (s[i] - '0');
		seen = 1;
	}
	if (!seen) return 0;
	*out = neg ? -v : v;
	return 1;
}

/* str2nv() -- coordinates and the like.  strtod() on a stack copy: the fields
 * are adjacent in the record (x ends where y begins, with no separator when
 * a coordinate is wide), so strtod() cannot be pointed at the buffer itself. */
static int str2nv(const char *s, STRLEN n, NV *out)
{
	char buf[64], *end;
	double v;
	if (n == 0 || n >= sizeof(buf)) return 0;
	memcpy(buf, s, n);
	buf[n] = '\0';
	errno = 0;
	v = strtod(buf, &end);
	if (end == buf) return 0;
	*out = (NV)v;
	return 1;
}

static int fld_iv(const char *line, STRLEN llen, STRLEN from, STRLEN to, IV *out)
{
	const char *s;
	STRLEN n = fld(line, llen, from, to, &s);
	return n ? str2iv(s, n, out) : 0;
}

static int fld_nv(const char *line, STRLEN llen, STRLEN from, STRLEN to, NV *out)
{
	const char *s;
	STRLEN n = fld(line, llen, from, to, &s);
	return n ? str2nv(s, n, out) : 0;
}

/* guess_element() -- only when columns 77-78 are absent, which happens in
 * files written before the element column existed and in files written by
 * programs that should know better.
 *
 * The atom name is right-justified from column 14 for one-letter elements and
 * from column 13 for two-letter ones, so " CA " is a carbon alpha and "CA  "
 * is a calcium.  That rule is worth following exactly, because the alternative
 * -- taking the first two letters -- turns every "HG11" hydrogen into mercury. */
static STRLEN guess_element(const char *raw, STRLEN rawlen, char *buf)
{
	if (rawlen == 0) return 0;
	/* A hydrogen with a long name -- HG11, HD22, HE21 -- fills all four
	 * columns and starts in column 13, exactly where a two-letter element
	 * starts.  Column position alone cannot separate the two, so take the
	 * full field as the tie-breaker: no two-letter element has a four
	 * character atom name, while nearly every hydrogen past the first does.
	 * Without this, every HG11 in the file becomes mercury. */
	if (rawlen >= 4 && raw[0] != ' ' && raw[1] != ' ' && raw[2] != ' ' && raw[3] != ' '
	    && (raw[0] == 'H' || raw[0] == 'D' || raw[0] == 'h' || raw[0] == 'd')) {
		buf[0] = (char)toupper((unsigned char)raw[0]);
		return 1;
	}
	/* a name that starts in column 13 with two letters is a two-letter
	 * element (FE, ZN, CL, MG); a digit there is a hydrogen count (1HB) */
	if (raw[0] != ' ' && isalpha((unsigned char)raw[0])
	    && rawlen >= 2 && isalpha((unsigned char)raw[1])) {
		buf[0] = (char)toupper((unsigned char)raw[0]);
		buf[1] = (char)toupper((unsigned char)raw[1]);
		return 2;
	}
	{	/* otherwise the first letter in the field is the element */
		STRLEN i;
		for (i = 0; i < rawlen; i++) {
			if (isalpha((unsigned char)raw[i])) {
				buf[0] = (char)toupper((unsigned char)raw[i]);
				return 1;
			}
		}
	}
	return 0;
}

/* --- options -------------------------------------------------------------- */

static SV *opt_get(pTHX_ HV *o, const char *k)
{
	SV **p;
	if (!o) return NULL;
	p = hv_fetch(o, k, (I32)strlen(k), 0);
	return (p && *p && SvOK(*p)) ? *p : NULL;
}

static IV opt_iv(pTHX_ HV *o, const char *k, IV dflt)
{
	SV *v = opt_get(aTHX_ o, k);
	return v ? SvIV(v) : dflt;
}

static int opt_bool(pTHX_ HV *o, const char *k, int dflt)
{
	SV *v = opt_get(aTHX_ o, k);
	return v ? (SvTRUE(v) ? 1 : 0) : dflt;
}

/* --- the parse ------------------------------------------------------------ */

#define NCOL 17 /* parallel per-atom columns */
static const char *const col_name[NCOL] = {
	"serial", "name", "altloc", "resname", "chain", "resseq", "icode",
	"x", "y", "z", "occupancy", "bfactor", "element", "charge",
	"het", "model", "line"
};
enum {
	C_SERIAL, C_NAME, C_ALTLOC, C_RESNAME, C_CHAIN, C_RESSEQ, C_ICODE,
	C_X, C_Y, C_Z, C_OCC, C_B, C_ELEMENT, C_CHARGE, C_HET, C_MODEL, C_LINENO
};

/* The per-residue sums, kept as sums rather than as means so that Perl can add
 * two of them together: a residue whose atoms are written in two runs -- an
 * alternate conformer group split apart, a ligand interleaved with the polymer
 * -- arrives here as two entries and is one residue by the time Perl is done
 * with it.  Means computed here could not be recombined without the counts,
 * and with the counts they may as well be sums. */
#define NRSUM 6
static const char *const res_sum_name[NRSUM] = { "sx", "sy", "sz", "n_xyz", "sb", "n_b" };
enum { R_SX, R_SY, R_SZ, R_NXYZ, R_SB, R_NB };

static void flush_residue(pTHX_ AV **rs, NV sx, NV sy, NV sz, IV nc, NV sb, IV nb)
{
	av_push(rs[R_SX],   nc ? newSVnv(sx) : newSVsv(&PL_sv_undef));
	av_push(rs[R_SY],   nc ? newSVnv(sy) : newSVsv(&PL_sv_undef));
	av_push(rs[R_SZ],   nc ? newSVnv(sz) : newSVsv(&PL_sv_undef));
	av_push(rs[R_NXYZ], newSViv(nc));
	av_push(rs[R_SB],   nb ? newSVnv(sb) : newSVsv(&PL_sv_undef));
	av_push(rs[R_NB],   newSViv(nb));
}

static HV *parse_buf(pTHX_ const char *buf, STRLEN len, HV *opts)
{
	HV *out  = newHV();
	HV *meta = newHV();
	HV *elements = newHV();
	AV *atom_hv = newAV();
	AV *col[NCOL];
	AV *res_sum[NRSUM];
	AV *res_first = newAV(), *res_last = newAV();
	AV *ter = newAV(), *model_nums = newAV();
	HV *want_chain = NULL;
	/* whole-structure statistics over the atoms that were kept */
	IV n_hydrogen = 0, n_water_atom = 0, bn = 0;
	NV bmin = 0, bmax = 0, bsum = 0;
	NV xmin = 0, ymin = 0, zmin = 0, xmax = 0, ymax = 0, zmax = 0;
	int have_bbox = 0;
	/* the residue being accumulated */
	NV rsx = 0, rsy = 0, rsz = 0, rsb = 0;
	IV rnc = 0, rnb = 0;
	IV want_model, n_models = 0, n_anisou = 0, n_skipped = 0, n_atom = 0;
	IV n_atom_rec = 0, n_het_rec = 0, cur_model = 1, lineno = 0;
	int keep_h, keep_water, keep_het, keep_meta, keep_anisou, keep_lineno, build_atoms;
	int i, have_res = 0;
	/* previous kept atom's residue identity, for boundary detection */
	char p_chain[8], p_icode[4], p_resname[8];
	IV p_resseq = 0, p_model = 0;
	int p_het = 0;
	STRLEN pos = 0;

	/* a negative model number means every model.  Zero cannot be the sentinel:
	 * an ensemble whose models are numbered from 0 is unusual but legal, and
	 * "model 0" would then quietly mean "all of them". */
	want_model  = opt_iv(aTHX_ opts, "model", 1);
	keep_h      = opt_bool(aTHX_ opts, "hydrogens", 1);
	keep_water  = opt_bool(aTHX_ opts, "waters", 1);
	keep_het    = opt_bool(aTHX_ opts, "hetatm", 1);
	keep_meta   = opt_bool(aTHX_ opts, "meta", 1);
	keep_anisou = opt_bool(aTHX_ opts, "anisou", 0);
	keep_lineno = opt_bool(aTHX_ opts, "lineno", 0);
	build_atoms = opt_bool(aTHX_ opts, "atom_hashes", 0);
	{
		SV *c = opt_get(aTHX_ opts, "chains");
		if (c && SvROK(c) && SvTYPE(SvRV(c)) == SVt_PVHV) want_chain = (HV *)SvRV(c);
	}
	p_chain[0] = p_icode[0] = p_resname[0] = '\0';

	for (i = 0; i < NCOL; i++)  col[i] = newAV();
	for (i = 0; i < NRSUM; i++) res_sum[i] = newAV();

	while (pos < len) {
		const char *line = buf + pos;
		const char *nl = (const char *)memchr(line, '\n', len - pos);
		STRLEN llen = nl ? (STRLEN)(nl - line) : (len - pos);
		pos += llen + (nl ? 1 : 0);
		lineno++;
		while (llen && (line[llen - 1] == '\r' || line[llen - 1] == ' ' || line[llen - 1] == '\t'))
			llen--; /* DOS line ends, and the trailing blanks of a padded record */
		if (llen == 0) continue;

		if (llen >= 6 && (memcmp(line, "ATOM  ", 6) == 0 || memcmp(line, "HETATM", 6) == 0)) {
			const char *s;
			const char *nm_raw;
			STRLEN nm_rawlen, n;
			char elbuf[4];
			STRLEN ellen;
			int het = (line[0] == 'H');
			res_info ri;
			int known;
			IV iv;
			char chain[4], icode[2], resname[8];
			STRLEN resname_len;

			if (het) n_het_rec++; else n_atom_rec++;
			if (want_model >= 0 && cur_model != want_model) { n_skipped++; continue; }
			if (het && !keep_het) { n_skipped++; continue; }

			/* residue name, columns 18-20 */
			n = fld(line, llen, 17, 19, &s);
			resname_len = n > sizeof(resname) - 1 ? sizeof(resname) - 1 : n;
			memcpy(resname, s, resname_len);
			resname[resname_len] = '\0';
			known = res_lookup(resname, resname_len, &ri);
			if (!keep_water && known && ri.type == RT_WATER) { n_skipped++; continue; }

			/* chain, column 22 -- with column 21 as a fallback, because a
			 * two-character chain id (some large assemblies) spills left */
			chain[0] = '\0';
			if (llen > 21 && line[21] != ' ') { chain[0] = line[21]; chain[1] = '\0'; }
			else if (llen > 20 && line[20] != ' ') { chain[0] = line[20]; chain[1] = '\0'; }
			if (want_chain) {
				if (!hv_exists(want_chain, chain, (I32)strlen(chain))) { n_skipped++; continue; }
			}

			/* atom name, columns 13-16, kept untrimmed for the element rule */
			nm_rawlen = 0;
			nm_raw = line;
			if (llen > 12) {
				STRLEN to = 15 >= llen ? llen - 1 : 15;
				nm_raw = line + 12;
				nm_rawlen = to - 12 + 1;
			}

			/* element, columns 77-78, guessed from the name when absent */
			ellen = fld(line, llen, 76, 77, &s);
			if (ellen) {
				STRLEN k;
				if (ellen > 2) ellen = 2;
				for (k = 0; k < ellen; k++) elbuf[k] = (char)toupper((unsigned char)s[k]);
			} else {
				ellen = guess_element(nm_raw, nm_rawlen, elbuf);
			}
			if (!keep_h && ellen == 1 && (elbuf[0] == 'H' || elbuf[0] == 'D')) { n_skipped++; continue; }

			/* --- kept ---------------------------------------------------
			 * The residue boundary is settled first, before this atom has
			 * been added to anything, so that closing the previous residue
			 * is a matter of flushing what is already there.  Everything
			 * the test needs is read from the record's own columns. */
			{
				IV rs = 0;
				int changed;
				fld_iv(line, llen, 22, 25, &rs);
				icode[0] = (llen > 26 && line[26] != ' ') ? line[26] : '\0';
				icode[1] = '\0';
				changed = !have_res
				        || rs != p_resseq
				        || p_model != cur_model
				        || p_het != het
				        || strcmp(p_chain, chain) != 0
				        || strcmp(p_icode, icode) != 0
				        || strcmp(p_resname, resname) != 0;
				if (changed) {
					if (have_res) {
						av_push(res_last, newSViv(n_atom - 1));
						flush_residue(aTHX_ res_sum, rsx, rsy, rsz, rnc, rsb, rnb);
					}
					rsx = rsy = rsz = rsb = 0; rnc = rnb = 0;
					av_push(res_first, newSViv(n_atom));
					have_res = 1;
					p_resseq = rs;
					p_model  = cur_model;
					p_het    = het;
					my_strlcpy(p_chain, chain, sizeof(p_chain));
					my_strlcpy(p_icode, icode, sizeof(p_icode));
					my_strlcpy(p_resname, resname, sizeof(p_resname));
				}
			}

			/* --- the atom's own fields ---------------------------------- */
			{
				const char *nm_s, *alt_s, *chg_s;
				STRLEN nm_n, alt_n, chg_n;
				IV serial = 0;
				int have_serial, have_occ;
				NV xv, yv, zv, bv, ov;
				int have_xyz = fld_nv(line, llen, 30, 37, &xv)
				             & fld_nv(line, llen, 38, 45, &yv)
				             & fld_nv(line, llen, 46, 53, &zv);
				int have_b = fld_nv(line, llen, 60, 65, &bv);

				have_occ    = fld_nv(line, llen, 54, 59, &ov);
				have_serial = fld_iv(line, llen, 6, 10, &serial);
				nm_n  = fld(line, llen, 12, 15, &nm_s);
				alt_n = fld(line, llen, 16, 16, &alt_s);
				chg_n = fld(line, llen, 78, 79, &chg_s);

				/* The sums and extremes are gathered here rather than in Perl
				 * because they have to touch every atom whether or not the
				 * caller wanted per-atom hashes.  Doing them in the loop that
				 * is already reading the numbers costs nothing; doing them
				 * again in Perl costs more than the whole parse. */
				if (have_xyz) {
					rsx += xv; rsy += yv; rsz += zv; rnc++;
					if (!have_bbox) {
						xmin = xmax = xv; ymin = ymax = yv; zmin = zmax = zv;
						have_bbox = 1;
					} else {
						if (xv < xmin) xmin = xv; else if (xv > xmax) xmax = xv;
						if (yv < ymin) ymin = yv; else if (yv > ymax) ymax = yv;
						if (zv < zmin) zmin = zv; else if (zv > zmax) zmax = zv;
					}
				}
				if (have_b) {
					rsb += bv; rnb++;
					if (!bn++) { bmin = bmax = bv; }
					else if (bv < bmin) bmin = bv;
					else if (bv > bmax) bmax = bv;
					bsum += bv;
				}
				if (ellen) {
					SV **cnt = hv_fetch(elements, elbuf, (I32)ellen, 1);
					if (cnt && *cnt) sv_inc(*cnt);
					if (ellen == 1 && (elbuf[0] == 'H' || elbuf[0] == 'D')) n_hydrogen++;
				}
				if (known && ri.type == RT_WATER) n_water_atom++;

				/* Two shapes to hand back, and never both, because building
				 * every atom twice -- once as columns here, once as a hash in
				 * Perl afterwards -- was costing more than everything else in
				 * the read put together.  The hash is what Structure::Info
				 * wants, and it is built here where the fields already are;
				 * the columns are what the low-level parse hands to anyone
				 * calling it directly. */
				if (build_atoms) {
					HV *a = newHV();
					(void)hv_stores(a, "name",   newSVpvn(nm_s, nm_n));
					(void)hv_stores(a, "serial", have_serial ? newSViv(serial) : newSVsv(&PL_sv_undef));
					(void)hv_stores(a, "altloc", newSVpvn(alt_s, alt_n));
					(void)hv_stores(a, "x", have_xyz ? newSVnv(xv) : newSVsv(&PL_sv_undef));
					(void)hv_stores(a, "y", have_xyz ? newSVnv(yv) : newSVsv(&PL_sv_undef));
					(void)hv_stores(a, "z", have_xyz ? newSVnv(zv) : newSVsv(&PL_sv_undef));
					(void)hv_stores(a, "occupancy", have_occ ? newSVnv(ov) : newSVsv(&PL_sv_undef));
					(void)hv_stores(a, "bfactor",   have_b   ? newSVnv(bv) : newSVsv(&PL_sv_undef));
					(void)hv_stores(a, "element", newSVpvn(elbuf, ellen));
					(void)hv_stores(a, "charge",  newSVpvn(chg_s, chg_n));
					(void)hv_stores(a, "hetero",  newSViv(het));
					av_push(atom_hv, newRV_noinc((SV *)a));
				} else {
					av_push(col[C_SERIAL], have_serial ? newSViv(serial) : newSVsv(&PL_sv_undef));
					av_push(col[C_NAME],   newSVpvn(nm_s, nm_n));
					av_push(col[C_ALTLOC], newSVpvn(alt_s, alt_n));
					av_push(col[C_X], have_xyz ? newSVnv(xv) : newSVsv(&PL_sv_undef));
					av_push(col[C_Y], have_xyz ? newSVnv(yv) : newSVsv(&PL_sv_undef));
					av_push(col[C_Z], have_xyz ? newSVnv(zv) : newSVsv(&PL_sv_undef));
					av_push(col[C_OCC], have_occ ? newSVnv(ov) : newSVsv(&PL_sv_undef));
					av_push(col[C_B],   have_b   ? newSVnv(bv) : newSVsv(&PL_sv_undef));
					av_push(col[C_ELEMENT], newSVpvn(elbuf, ellen));
					av_push(col[C_CHARGE],  newSVpvn(chg_s, chg_n));
				}
			}

			/* The residue's identity.  Perl reads these at the index a residue
			 * starts on, once per residue rather than once per atom, but they
			 * are emitted per atom because that is where they are read from. */
			av_push(col[C_RESNAME], newSVpvn(resname, resname_len));
			av_push(col[C_CHAIN], newSVpvn(chain, strlen(chain)));
			if (fld_iv(line, llen, 22, 25, &iv)) av_push(col[C_RESSEQ], newSViv(iv));
			else                                 av_push(col[C_RESSEQ], newSVsv(&PL_sv_undef));
			av_push(col[C_ICODE], newSVpvn(icode, icode[0] ? 1 : 0));
			av_push(col[C_HET], newSViv(het));
			av_push(col[C_MODEL], newSViv(cur_model));
			if (keep_lineno) av_push(col[C_LINENO], newSViv(lineno));

			n_atom++;
			continue;
		}

		if (llen >= 6 && memcmp(line, "ANISOU", 6) == 0) {
			n_anisou++;
			if (!keep_anisou) continue;
			/* fall through to meta */
		}

		if (llen >= 5 && memcmp(line, "MODEL", 5) == 0) {
			IV m;
			n_models++;
			cur_model = fld_iv(line, llen, 10, 13, &m) ? m : n_models;
			av_push(model_nums, newSViv(cur_model));
			continue;
		}
		if (llen >= 6 && memcmp(line, "ENDMDL", 6) == 0) continue;

		if (llen >= 3 && memcmp(line, "TER", 3) == 0) {
			HV *t = newHV();
			const char *s;
			STRLEN n;
			IV iv;
			n = fld(line, llen, 17, 19, &s); (void)hv_stores(t, "resname", newSVpvn(s, n));
			n = fld(line, llen, 21, 21, &s); (void)hv_stores(t, "chain",   newSVpvn(s, n));
			n = fld(line, llen, 26, 26, &s); (void)hv_stores(t, "icode",   newSVpvn(s, n));
			(void)hv_stores(t, "resseq", fld_iv(line, llen, 22, 25, &iv) ? newSViv(iv) : newSVsv(&PL_sv_undef));
			(void)hv_stores(t, "model", newSViv(cur_model));
			av_push(ter, newRV_noinc((SV *)t));
			continue;
		}

		/* everything else is a header/annotation record: keep the line whole
		 * and let Perl take it apart by column */
		if (keep_meta) {
			const char *s;
			STRLEN n = fld(line, llen, 0, 5, &s);
			if (n) {
				SV **slot = hv_fetch(meta, s, (I32)n, 0);
				AV *av;
				if (slot && *slot && SvROK(*slot)) {
					av = (AV *)SvRV(*slot);
				} else {
					av = newAV();
					(void)hv_store(meta, s, (I32)n, newRV_noinc((SV *)av), 0);
				}
				av_push(av, newSVpvn(line, llen));
			}
		}
	}
	if (have_res) {
		av_push(res_last, newSViv(n_atom - 1));
		flush_residue(aTHX_ res_sum, rsx, rsy, rsz, rnc, rsb, rnb);
	}

	(void)hv_stores(out, "atoms", newRV_noinc((SV *)atom_hv));
	for (i = 0; i < NRSUM; i++)
		(void)hv_store(out, res_sum_name[i], (I32)strlen(res_sum_name[i]),
		               newRV_noinc((SV *)res_sum[i]), 0);
	(void)hv_stores(out, "elements",     newRV_noinc((SV *)elements));
	(void)hv_stores(out, "n_hydrogens",  newSViv(n_hydrogen));
	(void)hv_stores(out, "n_water_atoms", newSViv(n_water_atom));
	if (bn) {
		HV *b = newHV();
		(void)hv_stores(b, "min",  newSVnv(bmin));
		(void)hv_stores(b, "max",  newSVnv(bmax));
		(void)hv_stores(b, "mean", newSVnv(bsum / (NV)bn));
		(void)hv_stores(b, "n",    newSViv(bn));
		(void)hv_stores(out, "bfactor_stats", newRV_noinc((SV *)b));
	} else {
		(void)hv_stores(out, "bfactor_stats", newSVsv(&PL_sv_undef));
	}
	if (have_bbox) {
		HV *bb = newHV();
		AV *ctr = newAV();
		(void)hv_stores(bb, "xmin", newSVnv(xmin));
		(void)hv_stores(bb, "ymin", newSVnv(ymin));
		(void)hv_stores(bb, "zmin", newSVnv(zmin));
		(void)hv_stores(bb, "xmax", newSVnv(xmax));
		(void)hv_stores(bb, "ymax", newSVnv(ymax));
		(void)hv_stores(bb, "zmax", newSVnv(zmax));
		av_push(ctr, newSVnv((xmin + xmax) / 2));
		av_push(ctr, newSVnv((ymin + ymax) / 2));
		av_push(ctr, newSVnv((zmin + zmax) / 2));
		(void)hv_stores(out, "bbox",   newRV_noinc((SV *)bb));
		(void)hv_stores(out, "center", newRV_noinc((SV *)ctr));
	} else {
		(void)hv_stores(out, "bbox",   newSVsv(&PL_sv_undef));
		(void)hv_stores(out, "center", newSVsv(&PL_sv_undef));
	}

	for (i = 0; i < NCOL; i++) {
		if (i == C_LINENO && !keep_lineno) { SvREFCNT_dec((SV *)col[i]); continue; }
		(void)hv_store(out, col_name[i], (I32)strlen(col_name[i]), newRV_noinc((SV *)col[i]), 0);
	}
	(void)hv_stores(out, "res_first",    newRV_noinc((SV *)res_first));
	(void)hv_stores(out, "res_last",     newRV_noinc((SV *)res_last));
	(void)hv_stores(out, "ter",          newRV_noinc((SV *)ter));
	(void)hv_stores(out, "meta",         newRV_noinc((SV *)meta));
	(void)hv_stores(out, "model_numbers", newRV_noinc((SV *)model_nums));
	(void)hv_stores(out, "n_atoms",      newSViv(n_atom));
	(void)hv_stores(out, "n_residues",   newSViv(av_len(res_first) + 1));
	(void)hv_stores(out, "n_models",     newSViv(n_models ? n_models : 1));
	(void)hv_stores(out, "n_anisou",     newSViv(n_anisou));
	(void)hv_stores(out, "n_skipped",    newSViv(n_skipped));
	(void)hv_stores(out, "n_atom_records",   newSViv(n_atom_rec));
	(void)hv_stores(out, "n_hetatm_records", newSViv(n_het_rec));
	(void)hv_stores(out, "n_lines",      newSViv(lineno));
	return out;
}

/* slurp() -- read the whole file.  Chunked rather than stat-then-read so that
 * a named pipe or /dev/stdin works the same as a file on disk. */
static char *slurp(pTHX_ const char *path, STRLEN *lenp)
{
	FILE *fh = fopen(path, "rb");
	char *buf;
	STRLEN cap = 1 << 20, len = 0;
	if (!fh) croak("Structure::Info: cannot read '%s': %s", path, Strerror(errno));
	Newx(buf, cap, char);
	for (;;) {
		size_t got;
		if (len == cap) {
			cap *= 2;
			Renew(buf, cap, char);
		}
		got = fread(buf + len, 1, cap - len, fh);
		len += got;
		if (got == 0) break;
	}
	if (ferror(fh)) {
		int e = errno;
		Safefree(buf);
		fclose(fh);
		croak("Structure::Info: error reading '%s': %s", path, Strerror(e));
	}
	fclose(fh);
	*lenp = len;
	return buf;
}

#line 824 "Info.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "static", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) static XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C static XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) static void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
static void
S_croak_xs_usage(const CV *const cv, const char *const params);

static void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

/* simple backcompat versions of the TARGx() macros with no optimisation */
#ifndef TARGi
#  define TARGi(iv, do_taint) sv_setiv_mg(TARG, iv)
#  define TARGu(uv, do_taint) sv_setuv_mg(TARG, uv)
#  define TARGn(nv, do_taint) sv_setnv_mg(TARG, nv)
#endif

#line 975 "Info.c"

XS_EUPXS(XS_Structure__Info__parse_file); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Structure__Info__parse_file)
{
    dVAR; dXSARGS;
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "path, opts = &PL_sv_undef");
    {
	SV *	path = ST(0)
;
	SV *	opts;
#line 823 "Info.xs"
		char *buf;
		STRLEN len;
		HV *o = NULL, *res;
		const char *p;
#line 992 "Info.c"
	SV *	RETVAL;

	if (items < 2)
	    opts = &PL_sv_undef;
	else {
	    opts = ST(1)
;
	}
#line 828 "Info.xs"
		if (!SvOK(path)) croak("Structure::Info: file name is undefined");
		if (SvOK(opts)) {
			if (!SvROK(opts) || SvTYPE(SvRV(opts)) != SVt_PVHV)
				croak("Structure::Info: options must be a hash reference");
			o = (HV *)SvRV(opts);
		}
		p = SvPV_nolen(path);
		buf = slurp(aTHX_ p, &len);
		res = parse_buf(aTHX_ buf, len, o);
		Safefree(buf);
		(void)hv_stores(res, "file", newSVsv(path));
		RETVAL = newRV_noinc((SV *)res);
#line 1014 "Info.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Structure__Info__parse_string); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Structure__Info__parse_string)
{
    dVAR; dXSARGS;
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "text, opts = &PL_sv_undef");
    {
	SV *	text = ST(0)
;
	SV *	opts;
#line 848 "Info.xs"
		STRLEN len;
		const char *buf;
		HV *o = NULL, *res;
#line 1036 "Info.c"
	SV *	RETVAL;

	if (items < 2)
	    opts = &PL_sv_undef;
	else {
	    opts = ST(1)
;
	}
#line 852 "Info.xs"
		if (!SvOK(text)) croak("Structure::Info: PDB text is undefined");
		if (SvOK(opts)) {
			if (!SvROK(opts) || SvTYPE(SvRV(opts)) != SVt_PVHV)
				croak("Structure::Info: options must be a hash reference");
			o = (HV *)SvRV(opts);
		}
		buf = SvPV_const(text, len);
		res = parse_buf(aTHX_ buf, len, o);
		RETVAL = newRV_noinc((SV *)res);
#line 1055 "Info.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Structure__Info_aa3to1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Structure__Info_aa3to1)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "name");
    {
	SV *	name = ST(0)
;
#line 868 "Info.xs"
		STRLEN n;
		const char *s;
		res_info ri;
#line 1076 "Info.c"
	SV *	RETVAL;
#line 872 "Info.xs"
		if (!SvOK(name)) croak("aa3to1: residue name is undefined");
		s = SvPV_const(name, n);
		RETVAL = (res_lookup(s, n, &ri) && ri.type == RT_AA)
		       ? newSVpvn(&ri.one, 1)
		       : newSVpvn("", 0);
#line 1084 "Info.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Structure__Info_res1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Structure__Info_res1)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "name");
    {
	SV *	name = ST(0)
;
#line 884 "Info.xs"
		STRLEN n;
		const char *s;
		res_info ri;
#line 1105 "Info.c"
	SV *	RETVAL;
#line 888 "Info.xs"
		if (!SvOK(name)) croak("res1: residue name is undefined");
		s = SvPV_const(name, n);
		RETVAL = (res_lookup(s, n, &ri) && ri.one)
		       ? newSVpvn(&ri.one, 1)
		       : newSVpvn("", 0);
#line 1113 "Info.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Structure__Info_res_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Structure__Info_res_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "name");
    {
	SV *	name = ST(0)
;
#line 900 "Info.xs"
		STRLEN n;
		const char *s;
		res_info ri;
		const char *t;
#line 1135 "Info.c"
	SV *	RETVAL;
#line 905 "Info.xs"
		if (!SvOK(name)) croak("res_type: residue name is undefined");
		s = SvPV_const(name, n);
		if (!res_lookup(s, n, &ri)) t = "other";
		else if (ri.type == RT_AA)    t = "amino_acid";
		else if (ri.type == RT_NUC)   t = "nucleotide";
		else if (ri.type == RT_WATER) t = "water";
		else                          t = "other";
		RETVAL = newSVpv(t, 0);
#line 1146 "Info.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C" {
#endif
XS_EXTERNAL(boot_Structure__Info); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Structure__Info)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Structure::Info::_parse_file", XS_Structure__Info__parse_file);
        newXS_deffile("Structure::Info::_parse_string", XS_Structure__Info__parse_string);
        newXS_deffile("Structure::Info::aa3to1", XS_Structure__Info_aa3to1);
        newXS_deffile("Structure::Info::res1", XS_Structure__Info_res1);
        newXS_deffile("Structure::Info::res_type", XS_Structure__Info_res_type);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

#ifdef __cplusplus
}
#endif
